package com.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import com.model.User;
import com.model.UserRepository;
import com.model.User_Detail_Repository;
import com.model.User_deatil;
import com.model.User_Language_Repository;
import com.model.User_Language;

@Controller    // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class MainContoller {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    @Autowired
    private User_Detail_Repository userDetailRepository;

    @Autowired
    private User_Language_Repository userLanguageRepository;

    private static final Logger logger = LoggerFactory.getLogger(MainContoller.class);

    /*@PostMapping(path="/add") // Map ONLY GET Requests
    public @ResponseBody String addNewUser (@RequestParam String name
            , @RequestParam String email) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        User n = new User();
        n.setName(name);
        n.setEmail(email);
        userRepository.save(n);
        return "Saved";
    }*/

    /*
    {
	    "email":"arvind@gmail.com",
	    "name":"arvind",
	    "password":"arvindtest"
    }
     */

//    @PostMapping(path = "/add")
//    public @ResponseBody String addNewUser(@RequestBody User u){
//        if (u!=null){
//
//            userRepository.save(u);
//            return "saved";
//
//        }else{
//
//            return "Error in User Data";
//
//        }
//
//    }


    /*
    {
        "user":{
            "email":"arvind@gmail.com",
            "name":"arvind",
            "password":"arvindtest"
        },
        "city":"surat",
        "contact":8401060120,
        "fname":"arvind",
        "lname":"modi"
    }
     */

    @PostMapping(path = "/add")
    public @ResponseBody String addNewUser(@RequestBody User_deatil ud){

        userDetailRepository.save(ud);
        return "saved";

    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<User> getAllUsers() {
        // This returns a JSON or XML with the users
        return userRepository.findAll();
    }

    @GetMapping(path = "/all_detail")
    public @ResponseBody Iterable<User_deatil> getAllUsers_Detail(){
        logger.info(userDetailRepository.findAll().toString());
        return userDetailRepository.findAll();
    }

    /* localhost:8087/demo/add_language?language=java */
    @GetMapping(path = "/add_language")
    public @ResponseBody String addNewLanguage(@RequestParam String language){
        logger.info(language);
        User_Language newlanguage = new User_Language();
        newlanguage.setLname(language);
        userLanguageRepository.save(newlanguage);
        return "saved";
    }

    /* localhost:8087/demo/all_language */
    @GetMapping(path = "/all_language")
    public @ResponseBody Iterable<User_Language> getAllLanguage(){
        return userLanguageRepository.findAll();
    }

}
